services:
  carga-horaria:
    container_name: carga-horaria
    image: carga-horaria
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/carga-horaria
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: carga-horaria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
